import esbuild from "esbuild";
import path from "node:path";
import process from "process";
import { builtinModules } from 'node:module';
import { fileURLToPath } from "node:url";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const projectRoot = path.dirname(fileURLToPath(import.meta.url));
const piAiBrowserRuntimePath = path.join(projectRoot, "src/core/agent-kernel/pi/PiAiBrowserRuntime.ts");
const piAgentCoreBrowserRuntimePath = path.join(projectRoot, "node_modules/@earendil-works/pi-agent-core/dist/agent.js");

const fridayPiAiBrowserRuntimePlugin = {
	name: "friday-pi-browser-runtime",
	setup(build) {
		build.onResolve({ filter: /^@earendil-works\/pi-ai$/ }, () => ({
			path: piAiBrowserRuntimePath,
		}));
		build.onResolve({ filter: /^@earendil-works\/pi-agent-core$/ }, () => ({
			path: piAgentCoreBrowserRuntimePath,
		}));
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	plugins: [fridayPiAiBrowserRuntimePlugin],
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
		...builtinModules.map((module) => `node:${module}`),
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
