import { App, Plugin } from "obsidian";
import { AgentService } from "../services/AgentService";
import { AgentActionService } from "../services/AgentActionService";
import { AgentRuntimeService, RuntimeWikiCompileSummary } from "../services/AgentRuntimeService";
import { AIService } from "../services/AIService";
import { CanvasService } from "../services/CanvasService";
import { ConversationService } from "../services/ConversationService";
import { DataService } from "../services/DataService";
import { SyncService } from "../services/SyncService";
import { ToolApprovalService } from "../services/ToolApprovalService";
import { CommandExecService } from "../services/CommandExecService";
import { InlineEditService } from "../services/InlineEditService";
import { WorkspaceAccessService } from "../services/WorkspaceAccessService";
import { SkillCommandService } from "../services/SkillCommandService";
import { SlashCommandService } from "../services/SlashCommandService";
import { AgentProfile } from "./agent";
import { ProjectEntry, ProjectGroupEntry } from "./project";
import { FridaySettings } from "./settings";
import { I18nParams, LocaleCode } from "../i18n/types";

export interface FridayPluginApi {
	app: App;
	manifest: Plugin["manifest"];
	settings: FridaySettings;
	dataService: DataService;
	syncService: SyncService;
	aiService: AIService;
	agentService: AgentService;
	conversationService: ConversationService;
	canvasService: CanvasService;
	agentActionService: AgentActionService;
	toolApprovalService: ToolApprovalService;
	commandExecService: CommandExecService;
	inlineEditService: InlineEditService;
	agentRuntimeService: AgentRuntimeService;
	workspaceAccessService: WorkspaceAccessService;
	skillCommandService: SkillCommandService;
	slashCommandService: SlashCommandService;
	addCommand: Plugin["addCommand"];
	registerView: Plugin["registerView"];
	addRibbonIcon: Plugin["addRibbonIcon"];
	addSettingTab: Plugin["addSettingTab"];
	saveSettings(): Promise<void>;
	upsertProject(project: ProjectEntry): Promise<void>;
	removeProject(slug: string): Promise<void>;
	setActiveProject(projectSlug: string): Promise<void>;
	compileWikiForActiveProject(rawPaths?: string[]): Promise<RuntimeWikiCompileSummary>;
	upsertProjectGroup(group: ProjectGroupEntry): Promise<void>;
	removeProjectGroup(groupId: string): Promise<void>;
	openSettingsTab(): void;
	openWorkspaceView(): Promise<void>;
	getLocale(): LocaleCode;
	t(key: string, params?: I18nParams): string;
	getPrimaryUserId(): string;
	getDetectedUserId(): string;
	getActiveAgent(): AgentProfile | null;
	setActiveAgent(agentId: string): Promise<void>;
	createAgent(input: { name: string; description: string; model?: string }): Promise<AgentProfile>;
}
