import { App, Plugin } from "obsidian";
import { AgentActionService } from "../services/AgentActionService";
import { AgentRuntimeService, RuntimeWikiCompileSummary } from "../services/AgentRuntimeService";
import { AIService } from "../services/AIService";
import { CanvasService } from "../services/CanvasService";
import { ConversationService } from "../services/ConversationService";
import { DataService } from "../services/DataService";
import { SyncService } from "../services/SyncService";
import { ToolApprovalService } from "../services/ToolApprovalService";
import { CommandExecService } from "../services/CommandExecService";
import { InlineEditService } from "../services/InlineEditService";
import { WorkspaceAccessService } from "../services/WorkspaceAccessService";
import { SkillCommandService } from "../services/SkillCommandService";
import { SlashCommandService } from "../services/SlashCommandService";
import { WorkbenchStateStore } from "../features/workbench/WorkbenchStateStore";
import { EventRouter } from "../core/execution/EventRouter";
import { ExecutionPlanner } from "../core/execution/ExecutionPlanner";
import { ExecutionOrchestrator } from "../core/execution/ExecutionOrchestrator";
import type { AgentRuntimeFacade } from "../core/agent-kernel/AgentKernel";
import { SyncEventBus } from "../features/sync/SyncEventBus";
import { SyncRuntimeStore } from "../features/sync/SyncRuntimeStore";
import { ProjectEntry, ProjectGitCredential, ProjectGroupEntry } from "./project";
import { FridaySettings } from "./settings";
import { SoulSummary } from "./soul";
import type { OfficialContentCatalogEntry, OfficialContentLegacyGuardState, OfficialContentSyncProgress } from "./officialContent";
import { I18nParams, LocaleCode } from "../i18n/types";
import { ProjectBoundaryService } from "../services/ProjectBoundaryService";
import type { GitRuntimeStatus } from "../platform/git/GitRuntimeProbe";
import type { PluginUpdateService } from "../services/PluginUpdateService";
import type { GroupModelCatalogService } from "../services/GroupModelCatalogService";
import type { LocalStateRootService } from "../services/LocalStateRootService";
import type { SoulStore } from "../services/SoulStore";
import type { RuntimeStateStore } from "../services/RuntimeStateStore";
import type { LegacyFridayRootMigrationService } from "../services/LegacyFridayRootMigrationService";
import type { LegacyAgentCleanupService } from "../services/LegacyAgentCleanupService";
import type { OnboardingService } from "../services/OnboardingService";

export type FridaySettingsSection = "user" | "project" | "sync" | "llm" | "soul" | "agent" | "subscriptions";

export interface OfficialContentServiceApi {
	refreshCatalog(): Promise<OfficialContentCatalogEntry[]>;
	applySubscriptions(): Promise<OfficialContentLegacyGuardState>;
	runBackgroundSync(onProgress?: (progress: OfficialContentSyncProgress) => void): Promise<void>;
	getBackgroundSyncProgress(): OfficialContentSyncProgress;
	runStartupCheck(): Promise<void>;
}

export interface FridayPluginApi {
	app: App;
	manifest: Plugin["manifest"];
	settings: FridaySettings;
	dataService: DataService;
	syncService: SyncService;
	aiService: AIService;
	conversationService: ConversationService;
	canvasService: CanvasService;
	agentActionService: AgentActionService;
	toolApprovalService: ToolApprovalService;
	commandExecService: CommandExecService;
	inlineEditService: InlineEditService;
	agentRuntimeService: AgentRuntimeService;
	agentRuntimeFacade: AgentRuntimeFacade;
	workspaceAccessService: WorkspaceAccessService;
	skillCommandService: SkillCommandService;
	slashCommandService: SlashCommandService;
	workbenchStateStore: WorkbenchStateStore;
	executionEventRouter: EventRouter;
	executionPlanner: ExecutionPlanner;
	executionOrchestrator: ExecutionOrchestrator;
	syncEventBus: SyncEventBus;
	syncRuntimeStore: SyncRuntimeStore;
	projectBoundaryService: ProjectBoundaryService;
	pluginUpdateService: PluginUpdateService;
	groupModelCatalogService: GroupModelCatalogService;
	officialContentService: OfficialContentServiceApi;
	onboardingService: OnboardingService;
	localStateRootService: LocalStateRootService;
	soulStore: SoulStore;
	runtimeStateStore: RuntimeStateStore;
	legacyFridayRootMigrationService: LegacyFridayRootMigrationService;
	legacyAgentCleanupService: LegacyAgentCleanupService;
	addCommand: Plugin["addCommand"];
	registerView: Plugin["registerView"];
	addRibbonIcon: Plugin["addRibbonIcon"];
	addSettingTab: Plugin["addSettingTab"];
	saveSettings(): Promise<void>;
	upsertProject(project: ProjectEntry): Promise<void>;
	removeProject(projectId: string): Promise<void>;
	setActiveProject(projectId: string): Promise<void>;
	getProjectGitCredential(projectId: string): Promise<ProjectGitCredential | null>;
	setProjectGitCredential(projectId: string, credential: ProjectGitCredential | null): Promise<void>;
	getUserGitCredential(): Promise<ProjectGitCredential | null>;
	setUserGitCredential(credential: ProjectGitCredential | null): Promise<void>;
	getCredentialStorageMode(): "secure" | "plaintext_local";
	setSyncMode(mode: FridaySettings["sync"]["mode"]): Promise<void>;
	setProjectAutoSync(projectId: string, enabled: boolean): Promise<void>;
	compileWikiForActiveProject(rawPaths?: string[], forceRebuild?: boolean): Promise<RuntimeWikiCompileSummary>;
	upsertProjectGroup(group: ProjectGroupEntry): Promise<void>;
	removeProjectGroup(groupId: string): Promise<void>;
	openSettingsTab(section?: FridaySettingsSection): void;
	openWorkspaceView(placement?: FridaySettings["workbench"]["startupPlacement"]): Promise<void>;
	reloadFridayPlugin(): Promise<void>;
	reloadObsidianApp(): void;
	getLocale(): LocaleCode;
	t(key: string, params?: I18nParams): string;
	getGitRuntimeStatus(): Promise<GitRuntimeStatus>;
	getPrimaryUserId(): string;
	getDetectedUserId(): string;
	listSouls(): SoulSummary[];
	getActiveSoul(): SoulSummary | null;
	setActiveSoul(soulId: string): Promise<void>;
	createSoul(input: { name: string; summary: string; description?: string }): Promise<SoulSummary>;
	canResetBuiltInSoulPreset(soulId: string): boolean;
	resetBuiltInSoulPreset(soulId: string): Promise<SoulSummary>;
}
